// <auto-generated />
using System;
using DatabaseStudyApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseStudyApp.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20210417115644_Entity FIX")]
    partial class EntityFIX
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DatabaseStudyApp.Entity.Music", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MusicGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("_created");

                    b.Property<DateTime?>("RecordDeleted")
                        .HasColumnType("datetime2")
                        .HasColumnName("_deleted");

                    b.Property<DateTime?>("RecordUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("_updated");

                    b.HasKey("Id");

                    b.HasIndex("MusicGroupId");

                    b.ToTable("Musics");
                });

            modelBuilder.Entity("DatabaseStudyApp.Entity.MusicGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("_created");

                    b.Property<DateTime?>("RecordDeleted")
                        .HasColumnType("datetime2")
                        .HasColumnName("_deleted");

                    b.Property<DateTime?>("RecordUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("_updated");

                    b.HasKey("Id");

                    b.ToTable("MusicGroups");
                });

            modelBuilder.Entity("DatabaseStudyApp.Entity.Music", b =>
                {
                    b.HasOne("DatabaseStudyApp.Entity.MusicGroup", "MusicGroup")
                        .WithMany("Musics")
                        .HasForeignKey("MusicGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicGroup");
                });

            modelBuilder.Entity("DatabaseStudyApp.Entity.MusicGroup", b =>
                {
                    b.Navigation("Musics");
                });
#pragma warning restore 612, 618
        }
    }
}
